# Generated by Django 3.0.2 on 2020-01-16 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Manufacturer'),
        ),
    ]
